### ISSUE TITLE
The following actions uses node12 which is deprecated and will be forced to run on node16

### ISSUE THREAD

**Issue by clausjoergensen** [DataDog/upload-dsyms-github-action#171]
The following actions uses node12 which is deprecated and will be forced to run on node16: DataDog/upload-dsyms-github-action@v0.2.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by maxep** [comment]
Hey @clausjoergensen 👋 

We have release [v0.3.0](https://github.com/DataDog/upload-dsyms-github-action/releases/tag/v0.3.0) which is based on Node 20.
